### ISSUE TITLE
Offerta: 10 ordinazioni scelte casualmente tra quelle fatte tra le 18:00 e le 19:00 sono regalate

### ISSUE THREAD

**Issue by damianomason** [damianomason/TOS-assignment2#8]

**Comment by Dam-99** [comment]
Nel file TakeAwayManagerTest.java è presente un `import java.util.*` nel commit di chiusura di questa issue a causa dell'IDE IntelliJ che ha automaticamente ottimizzato la lista degli import. Il modulo sembra non controllare le classi di test ed è quindi sfuggito al controllo.
